// Devocional diário: um por dia, em rodízio. Reflexões, gestos e orações originais deste projeto;
// versículos em tradução livre.
window.DEVOCIONAL = [
  { theme: 'Confiança', verse: 'Não se perturbe o vosso coração. Credes em Deus, crede também em mim.', ref: 'Jo 14,1',
    text: 'Jesus diz essas palavras na véspera da Paixão, sabendo o que viria. A paz que ele oferece não depende de tudo estar bem; depende de estarmos com ele. Hoje, quando o coração se agitar, lembre-se de que você não precisa controlar tudo.',
    act: 'Escreva num papel uma preocupação e, ao lado, “Jesus, eu confio em Vós”. Guarde no bolso.',
    pray: 'Senhor, acalma meu coração perturbado. Eu creio em Ti; aumenta a minha fé. Amém.' },
  { theme: 'Descanso', verse: 'Vinde a mim, todos os que estais cansados e sobrecarregados, e eu vos darei descanso.', ref: 'Mt 11,28',
    text: 'O convite de Jesus não é “esforce-se mais”, é “vinde”. Há um cansaço que nenhuma noite de sono resolve: o de carregar tudo sozinho. Deus não se impressiona com a nossa exaustão; ele a acolhe.',
    act: 'Tire cinco minutos hoje sem celular, apenas sentado, respirando devagar e repetindo: “Eu vou a Ti, Senhor”.',
    pray: 'Jesus, venho a Ti com o meu cansaço. Dá-me o Teu descanso. Amém.' },
  { theme: 'Presente', verse: 'Não vos preocupeis com o dia de amanhã: o dia de amanhã terá as suas preocupações. A cada dia basta o seu cuidado.', ref: 'Mt 6,34',
    text: 'A ansiedade vive no futuro; a graça chega no presente. Deus dá o maná de cada dia, não o estoque do mês. O que você precisa viver hoje, e só hoje?',
    act: 'Faça uma lista com apenas três tarefas para hoje. O resto espera.',
    pray: 'Pai, dá-me o pão de hoje e a força para o passo de hoje. O amanhã é Teu. Amém.' },
  { theme: 'Misericórdia', verse: 'Deus é maior que o nosso coração e conhece todas as coisas.', ref: '1Jo 3,20',
    text: 'Às vezes a voz mais dura que ouvimos é a nossa. Deus não é o acusador: ele conhece nossas fraquezas melhor que nós e, mesmo assim, nos ama. Deixe que o olhar dele corrija o seu.',
    act: 'Diga a si mesmo, em voz baixa, uma frase gentil que você diria a um amigo querido.',
    pray: 'Senhor, Tu és maior que o meu coração. Ensina-me a me olhar com a Tua misericórdia. Amém.' },
  { theme: 'Medo', verse: 'Não temas, porque eu te resgatei; chamei-te pelo teu nome: tu és meu.', ref: 'Is 43,1',
    text: 'Deus não diz “não haverá águas”; diz “quando atravessares as águas, estarei contigo” (Is 43,2). O medo não some por decreto, mas perde força quando lembramos a quem pertencemos.',
    act: 'Leia Isaías 43,1-5 devagar, trocando “Jacó” e “Israel” pelo seu nome.',
    pray: 'Senhor, Tu me chamas pelo nome. Sou Teu. Diante disso, o medo não tem a última palavra. Amém.' },
  { theme: 'Ajuda', verse: 'Carregai o peso uns dos outros.', ref: 'Gl 6,2',
    text: 'A vida cristã não é um esporte individual. Pedir ajuda é deixar que outro cumpra a lei de Cristo por meio de você. E oferecer ajuda é uma forma poderosa de sair do próprio labirinto.',
    act: 'Mande hoje uma mensagem a alguém: para pedir apoio ou para oferecer.',
    pray: 'Senhor, dá-me humildade para pedir e generosidade para oferecer. Amém.' },
  { theme: 'Gratidão', verse: 'Em tudo dai graças, porque esta é a vontade de Deus a vosso respeito.', ref: '1Ts 5,18',
    text: '“Em tudo”, não “por tudo”: não se agradece pelo sofrimento, mas dentro dele é possível encontrar pequenas graças. A gratidão treina o olhar para ver o que ainda está de pé.',
    act: 'Antes de dormir, anote três pequenas coisas boas do dia, por menores que sejam.',
    pray: 'Obrigado, Senhor, pelas graças que eu vi e pelas que não percebi. Amém.' },
  { theme: 'Silêncio', verse: 'Ficai quietos e sabei que eu sou Deus.', ref: 'Sl 46,11',
    text: 'Vivemos cercados de ruído, e muitas vezes o maior barulho está dentro de nós. O silêncio não é vazio: é espaço para Deus falar e para a alma respirar.',
    act: 'Use o temporizador de silêncio por três minutos. Se vierem pensamentos, deixe-os passar.',
    pray: 'Senhor, faz silêncio em mim, para que eu possa ouvir-Te. Amém.' },
  { theme: 'Queda', verse: 'O justo cai sete vezes e se levanta.', ref: 'Pr 24,16',
    text: 'O provérbio não diz que o justo não cai; diz que ele se levanta. Recaídas em velhos medos, hábitos ou tristezas não anulam o caminho. O que importa é o próximo passo.',
    act: 'Pense numa área em que você “caiu” recentemente. Qual é o menor passo para se levantar hoje?',
    pray: 'Senhor, quando eu cair, estende-me a mão. E que eu não desista de mim. Amém.' },
  { theme: 'Maria', verse: 'Fazei tudo o que ele vos disser.', ref: 'Jo 2,5',
    text: 'Em Caná, Maria percebe a falta antes de todos e a leva a Jesus. Ela faz o mesmo com as nossas faltas: não resolve no lugar de Jesus, mas nos conduz até ele.',
    act: 'Reze uma dezena do terço entregando a Maria aquilo que está faltando em sua vida.',
    pray: 'Maria, Mãe atenta, leva a Jesus o que me falta e ensina-me a fazer o que ele disser. Amém.' },
  { theme: 'Esperança', verse: 'Os que esperam no Senhor renovam as suas forças; sobem com asas como águias.', ref: 'Is 40,31',
    text: 'Esperar no Senhor não é ficar parado; é caminhar apoiado em outra força que não a nossa. As águias não batem as asas o tempo todo: aproveitam as correntes de ar.',
    act: 'Saia ao ar livre por alguns minutos e olhe para o céu. Agradeça por estar vivo.',
    pray: 'Senhor, renova as minhas forças. Que eu aprenda a me apoiar em Ti. Amém.' },
  { theme: 'Corpo', verse: 'Não sabeis que o vosso corpo é templo do Espírito Santo?', ref: '1Cor 6,19',
    text: 'Cuidar do corpo também é oração: dormir, comer bem, caminhar, tomar sol, tomar o remédio prescrito. A saúde mental passa pelo corpo, e o corpo é morada de Deus.',
    act: 'Escolha um cuidado concreto com o corpo hoje: beber mais água, dormir mais cedo ou caminhar 15 minutos.',
    pray: 'Espírito Santo, ensina-me a cuidar do templo que Tu habitas. Amém.' },
  { theme: 'Perdão', verse: 'Perdoai, e sereis perdoados.', ref: 'Lc 6,37',
    text: 'Guardar mágoa é como carregar uma pedra no peito. Perdoar não é dizer que não doeu nem que tudo volta a ser como antes; é decidir não deixar que a ferida governe a vida.',
    act: 'Pense em alguém a quem precisa perdoar. Se não conseguir ainda, reze: “Senhor, eu quero querer perdoar”.',
    pray: 'Pai, perdoa as minhas ofensas assim como eu perdoo, e dá-me a graça de perdoar de verdade. Amém.' },
  { theme: 'Presença', verse: 'Eis que estou convosco todos os dias, até o fim dos tempos.', ref: 'Mt 28,20',
    text: 'Todos os dias: os bons, os ruins, os comuns. Não há dia em que Jesus tenha folga da nossa vida. Você pode conversar com ele agora, do jeito que está.',
    act: 'Ao longo do dia, faça três pausas de dez segundos e diga: “Tu estás aqui”.',
    pray: 'Jesus, obrigado por estares comigo todos os dias. Que eu perceba a Tua presença hoje. Amém.' }
];
